name: Build and deploy .NET Core application to Web App FTAcademyStudentMnagementAPI 

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to the 'main' branch

env:
  AZURE_WEBAPP_NAME: FTAcademyStudentMnagementAPI # Name of your Azure Web App
  WEB_PROJECT_PATH: FTACADEMY_STUDENT_MANAGEMENT_API/FTACADEMY_STUDENT_MANAGEMENT_API.csproj
  AZURE_WEBAPP_PACKAGE_PATH: ./published_app_output
  CONFIGURATION: Release # Build configuration (e.g., Debug, Release)
  DOTNET_CORE_VERSION: 8.0.x # .NET SDK version to use

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner for .NET development
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore NuGet packages
      run: dotnet restore "${{ env.WEB_PROJECT_PATH }}"

    - name: Build Project
      run: dotnet build "${{ env.WEB_PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Run Tests
      # IMPORTANT: If you don't have a test project or this step fails, you can remove it.
      run: dotnet test "${{ env.WEB_PROJECT_PATH }}" --no-build

    - name: Publish Application
      run: dotnet publish "${{ env.WEB_PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

    - name: List Published Files (for debugging)
      run: dir "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      continue-on-error: true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest # Use a Windows runner for deployment
    needs: build # This ensures the 'deploy' job runs only after the 'build' job completes successfully
    steps:
    - name: Download Artifact from Build Job
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    # REMOVE THIS STEP: You do NOT need azure/login when using a publish profile with azure/webapps-deploy
    # - name: Azure Login
    #   uses: azure/login@v2
    #   with:
    #     publish-profile: ${{ secrets.FTACADEMYSTUDENTMNAGEMENTAPI }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2   # This action will handle the authentication using the publish profile you provide
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # The name of the Azure Web App
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} # The path to the package to deploy
        # Pass the publish profile directly to azure/webapps-deploy
        publish-profile: ${{ secrets.FTACADEMYSTUDENTMNAGEMENTAPI }} # Your Azure publish profile secret
